---
spring:
  profiles:
    active: dev 
hello: hello dev, welcome to config server.
security.user.password: mysecret_dev

---
spring:
  profiles:
    active: pro 
hello: hello pro, welcome to config server.
security.user.password: mysecret_pro