---
spring:
  profiles:
    active: pro 
hello: hello pro, welcome to config server pro2.
security.user.password: mysecret_pro2_refresh
store.mail.mq.queue: email_queue
store.mail.mq.exchange: email_exchange
store.mail.mq.routkey: email_routkey
